<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('product')
            ->insert(
                [
                    [
                        'product_name' => 'YZF R1',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '1',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'YZF R6',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '1',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'YZF R3',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '1',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CBR1000RR FireBlade',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '2',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CBR600RR',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '2',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CBR250RR',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '2',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CBR650R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '2',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CBR500R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '2',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'GSX R1000',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '3',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'GSX R750',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '3',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'GSX R600',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '3',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'ZX10-RR',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '4',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'ZX6-R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '4',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'ZX25-R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '4',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],

                    [
                        'product_name' => 'Ninja 400',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '4',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Ninja 650',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '4',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'S1000RR',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '5',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Panigale V4',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '6',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Panigale 1299R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '6',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Panigale 1199',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '6',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Panigale 1198',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '6',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Panigale 959',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '6',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => '848 EVO',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '6',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Super Sport',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '6',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'RSV4',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '7',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'RSV4 11000 Factory',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '7',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'RS 660',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '7',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => '1190 RC8-R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '8',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'F4-RC',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '9',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'F4 LH44',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '9',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'F3 800RC',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '9',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'F3 675 Super Sport',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '9',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Daytona Moto2 765',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '10',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Daytona 675 Triple',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '10',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'MT-10',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '11',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'MT-09',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '11',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'MT-07',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '11',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'MT-03',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '11',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CB1000R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '12',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CB1000',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '12',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CB650R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '12',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CB650',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '12',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CB500R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '12',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CB300R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '12',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'GSX S1000',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '13',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Virus 1000',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '13',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'GSX S750',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '13',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Katana 1000',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '13',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Z1000',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '14',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Z900',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '14',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Z800',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '14',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Z650',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '14',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Z300',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '14',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Z-H2',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '14',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'S1000R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '15',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'R1250R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '15',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'G310R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '15',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Monster 1100 Evo',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '16',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Monster 1200R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '16',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Monster 821',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '16',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Monster 797',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '16',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Monster 796',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '16',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Monster 795',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '16',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Street Fighter 1098S',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '16',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Street Fighter 848 Evo',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '16',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Street Fighter V4',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '16',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'XDiavel',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '16',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Shiver 900',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '17',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Tuono V4',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '17',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => '1290 Super Duke',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '18',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => '790 Duke',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '18',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => '390 Duke',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '18',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => '250 Duke',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '18',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Brutale 800RR',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '19',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Brutale 1000 Serie Oro',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '19',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Dragster 800RR',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '19',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Revale 800',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '19',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Street Triple RS',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '20',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Speed Triple R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '20',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'XSR900',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '21',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CB1100',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '22',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CB750',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '22',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CB400',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '22',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Srcambler 1100',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '26',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Scrambler Cafe Racer',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '26',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Scrambler Icon',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '26',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Bonneville T100',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '30',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Street Twin',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '30',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Street Scrambler',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '30',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Goldwing',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '32',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'ZX16-R',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '34',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'K1600',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '35',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'CB500X',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '42',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Africa Twin',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '42',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'V-Strom 1000',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '43',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'V-Strom 650',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '43',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Versys 1000',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '44',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Versys 650',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '44',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Versys 300',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '44',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'R1200 GS',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '45',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'R1250 GSA',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '45',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'F850 GS',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '45',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'R9T',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '25',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Multistrada 1260',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '46',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Multistrada 950 S',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '46',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Caponord 1200 Rally',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '47',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => '1190 Adventure',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '48',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Turismo Veloce SCS',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '49',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Tiger 1200 Explorer',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '50',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => 'Hypermotard 821',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '56',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                    [
                        'product_name' => '450 Rally Replica',
                        'product_desc' => '',
                        'product_content' => '',
                        'brand_category_id' => '58',
                        'product_price' => '1000',
                        'product_promotion_price' => '900',
                        'product_stock' => '100',
                        'product_rate' => '5',
                        'product_created_at' => time(),
                        'product_created_by' => 1,
                    ],
                ]
            );
    }
}
